/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sina.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.sina.domain.Users;
import com.sina.service.UsersService;
import com.sina.struts.form.UsersForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-25-2011
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="usersForm" parameter="flag" scope="request"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsersForm usersForm = (UsersForm) form;// TODO Auto-generated method stub
		//这里需要调用service 类完成验证
		//根据用户的输入，我们创建user对象
		Users user=new Users();
		user.setName(usersForm.getName());
		user.setPasswd(usersForm.getPasswd());
		
		//创建Servcie
		UsersService usersService=new UsersService();
		user=usersService.checkUser(user);
		if(user!=null){
			request.getSession().setAttribute("userinfo", user);
			return mapping.findForward("loginok");
		}else{
			return mapping.findForward("loginerr");
		}
		
	}
}